<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtoh0dy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtoh0dy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUtoh0dy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUtoh0dy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUtoh0dy\appProdProjectContainer(array(
    'container.build_hash' => 'Utoh0dy',
    'container.build_id' => 'cc01288e',
    'container.build_time' => 1517229733,
));
