<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5hde2ta\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5hde2ta/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5hde2ta.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5hde2ta\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5hde2ta\appDevDebugProjectContainer(array(
    'container.build_hash' => '5hde2ta',
    'container.build_id' => 'a40bcc7e',
    'container.build_time' => 1523273630,
));
